name: edit
version: 0.6.0+qlever
usage: edit a release
description: |-
  Edit a release.
ignoreFlags: false
useTunnel: true
platformCommand:
  - command: ${HELM_PLUGIN_DIR}/helm-edit
  - command: ${HELM_PLUGIN_DIR}\helm-edit.exe
    os: windows
platformHooks:
  install:
    - command: ${HELM_PLUGIN_DIR}/install.ps1
      os: windows
    - command: ${HELM_PLUGIN_DIR}\install.sh
