name: "edit"
version: "0.6.0+qlever"
usage: "edit a release"
description: |-
  Edit a release.
ignoreFlags: false
useTunnel: true
command: "$HELM_PLUGIN_DIR/helm-edit"
platformHooks:
  install:
    - command: "$HELM_PLUGIN_DIR/install.ps1"
      os: windows
    - command: "$HELM_PLUGIN_DIR/install.sh"
