name: Go

on:
  push:
    branches: [master]
    tags:
      - "*"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          skip-go-installation: true

      - name: Build
        run: go build -v ./...
        if: startsWith(github.ref, 'refs/heads/')

      - name: Test
        run: go test -v ./...
        if: startsWith(github.ref, 'refs/heads/')

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
